# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1



jobs:
  setup:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)

  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: cat $HOME/.gradle/gradle.properties | cut -d'=' -f 1
      - run: ./gradlew clean build

  publish:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - run: ./gradlew clean build
#      - run: cat ./build/manifest/gradle-extended-info-plugin.properties
#      - run: if [ "$BRANCH" == "master" ]; then ./gradlew clean verifyRelease createRelease; fi
#      - run: if [ "$BRANCH" == "master" ]; then ./gradlew clean build; fi
#      - run: if [ "$BRANCH" == "master" ]; then git push --tags; fi
#      - run: if [ "$BRANCH" == "master" ]; then ./gradlew bintrayUpload; fi
#      - run: if [ "$BRANCH" == "master" ]; then ./gradlew publishPlugins; fi

workflows:
  build_and_test:
    jobs:
      - setup:
          context: boxhead-builds
      - build:
          context: boxhead-builds
      - pubish:
          context: boxhead-builds